### ISSUE TITLE
Different output running with grunt-contrib-nodeunit vs plain nodeunit

### ISSUE THREAD

**Issue by srlmproductions** [gruntjs/grunt-contrib-nodeunit#32]
I'm getting materially different outputs when I use this grunt-contrib-nodeunit when compared to running nodeunit directly. Here's the code:

test.js
```
exports.testSomethingElse = function(test){
    test.expect(1);
    setTimeout(function(){
        setTimeout(function(){
            var t;
            t();
        }, 10);
        test.ok(true);
        //test.done(); 
    },100);
};
```

Gruntfile.js
```
module.exports = function (grunt) {
    grunt.initConfig({
        pkg: grunt.file.readJSON('package.json'),
        nodeunit: {
            all: ['test.js'],
            options: {
                reporter: 'default'
            }
        }
    });

    grunt.loadNpmTasks('grunt-contrib-nodeunit');
    grunt.registerTask('default',['nodeunit']);
};
```

package.json
```
{
    "name": "test",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
        "grunt": "latest",
        "nodeunit": "latest",
        "grunt-contrib-nodeunit": "latest"
    }
}
```

Here's the output:
```
user@desktop:~/bug_test$ nodeunit test.js 

test.js

FAILURES: Undone tests (or their setups/teardowns): 
- testSomethingElse

To fix this, make sure all tests call test.done()
user@desktop:~/bug_test$ grunt
Running "nodeunit:all" (nodeunit) task

test.js
Fatal error: undefined is not a function
```

Notice how when I run it in nodeunit it gives the error message of "Undone tests", while if I run it in grunt it catches the "undefined is not a function" error.

If we comment out the `test.done()` line then we get the following output:
```
user@desktop:~/bug_test$ nodeunit test.js 

test.js
✔ testSomethingElse

OK: 1 assertions (104ms)

/home/user/bug_test/test.js:6
            t();
            ^
TypeError: undefined is not a function
    at null._onTimeout (/home/user/bug_test/test.js:6:13)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
user@desktop:~/bug_test$ grunt
Running "nodeunit:all" (nodeunit) task

test.js
✔ testSomethingElse

OK: 1 assertions (105ms)

Done, without errors.
```
Again, notice how nodeunit prints out a stacktrace even though the tests passed, while grunt-contrib-nodeunit hides that.

Is there a solution to this problem?

**Comment by nicjansma** [comment]
#33 was merged in to improve the documentation.
